import type { NextPage } from "next"
import Head from "next/head"
import React from "react"
import Callout from "../components/callout"
import MyButton from "../components/my-button"
import Spinner from "../components/spinner"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Callout
        text="Ma! This is from URL"
        onTap={() => {
          console.log("hi")
        }}
      />
      <Spinner />
      {/* addFont() issue */}
      <MyButton />
    </div>
  )
}

export default Home
